# Generated by Django 5.2.7 on 2025-10-06 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, verbose_name='Genre')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='Antécédents médicaux')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergies')),
                ('current_medications', models.TextField(blank=True, null=True, verbose_name='Médicaments actuels')),
                ('blood_type', models.CharField(blank=True, max_length=5, null=True, verbose_name='Groupe sanguin')),
                ('emergency_contact_name', models.CharField(max_length=100, verbose_name="Contact d'urgence")),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name="Téléphone d'urgence")),
                ('emergency_contact_relation', models.CharField(max_length=50, verbose_name='Lien de parenté')),
                ('insurance_provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assureur')),
                ('insurance_number', models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'assurance")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='Médecin traitant')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
