# Generated by Django 5.2.7 on 2025-10-08 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='primary_doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_patients', to=settings.AUTH_USER_MODEL, verbose_name='Médecin traitant'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='Médecin'),
        ),
        migrations.CreateModel(
            name='PatientSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Raison pour laquelle le patient est référé à ce spécialiste', null=True, verbose_name='Motif de consultation')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles sur le suivi avec le spécialiste', null=True, verbose_name='Notes')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'assignation")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_specialists', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='patients.patient', verbose_name='Patient')),
                ('specialist', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_patients', to=settings.AUTH_USER_MODEL, verbose_name='Médecin spécialiste')),
            ],
            options={
                'verbose_name': 'Spécialiste Patient',
                'verbose_name_plural': 'Spécialistes Patients',
                'db_table': 'patient_specialists',
                'ordering': ['-assigned_at'],
                'unique_together': {('patient', 'specialist')},
            },
        ),
    ]
