# Generated by Django 4.2.7 on 2025-11-10 21:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_patient_primary_doctor_alter_patient_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)], verbose_name='Tension systolique (mmHg)')),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)], verbose_name='Tension diastolique (mmHg)')),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)], verbose_name='Fréquence cardiaque (bpm)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température (°C)')),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(60)], verbose_name='Fréquence respiratoire (bpm)')),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(100)], verbose_name='Saturation en oxygène (%)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)], verbose_name='Taille (cm)')),
                ('waist_circumference', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tour de taille (cm)')),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='IMC')),
                ('health_status', models.CharField(choices=[('good', 'Bon'), ('fair', 'Moyen'), ('poor', 'Mauvais')], default='good', max_length=50, verbose_name='État général')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de mesure')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_medical_records', to=settings.AUTH_USER_MODEL, verbose_name='Médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Dossier médical du patient',
                'verbose_name_plural': 'Dossiers médicaux des patients',
                'db_table': 'patient_medical_records',
                'ordering': ['-recorded_at', '-created_at'],
                'indexes': [models.Index(fields=['patient', '-recorded_at'], name='patient_med_patient_3cfc1d_idx')],
            },
        ),
    ]
