# Generated by Django 4.2.7 on 2025-11-30 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0003_patientmedicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du médicament')),
                ('dosage', models.CharField(max_length=100, verbose_name='Dosage')),
                ('frequency', models.CharField(max_length=100, verbose_name='Fréquence')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Durée')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instructions')),
                ('status', models.CharField(choices=[('active', 'En cours'), ('stopped', 'Arrêté'), ('completed', 'Terminé')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medicaments', to=settings.AUTH_USER_MODEL, verbose_name='Médecin prescripteur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'db_table': 'patient_medicaments',
                'ordering': ['-start_date'],
            },
        ),
    ]
