# Generated by Django 4.2.7 on 2025-11-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_medicament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='duration',
        ),
        migrations.AddField(
            model_name='medicament',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (jours)'),
        ),
    ]
