# Generated by Django 4.2.7 on 2025-10-08 07:49

from django.db import migrations, models


def handle_duplicate_phones(apps, schema_editor):
    """
    Handle duplicate phone numbers by:
    1. Setting duplicate phone numbers to NULL (except the first occurrence)
    2. This allows the unique constraint to be applied
    """
    User = apps.get_model('accounts', 'User')
    
    # Get all phone numbers that appear more than once
    from django.db.models import Count
    duplicate_phones = (
        User.objects.values('phone')
        .annotate(count=Count('id'))
        .filter(count__gt=1, phone__isnull=False)
        .exclude(phone='')
    )
    
    for item in duplicate_phones:
        phone = item['phone']
        # Get all users with this phone number
        users_with_phone = User.objects.filter(phone=phone).order_by('id')
        
        # Keep the first one, set others to NULL
        first_user = True
        for user in users_with_phone:
            if first_user:
                first_user = False
                continue
            user.phone = None
            user.save()


def reverse_migration(apps, schema_editor):
    # No need to reverse the data cleanup
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # First, clean up duplicate phone numbers
        migrations.RunPython(handle_duplicate_phones, reverse_migration),
        
        # Then apply the unique constraint
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
