# Generated by Django 5.2.7 on 2025-10-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_emergency_contact_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_needs_reset',
            field=models.BooleanField(default=False, help_text='True if user needs to set their password on first login'),
        ),
    ]
