# Generated by Django 5.2.7 on 2025-10-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_password_needs_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('general', 'Médecin Généraliste'), ('cardiology', 'Cardiologie'), ('dermatology', 'Dermatologie'), ('pediatrics', 'Pédiatrie'), ('gynecology', 'Gynécologie'), ('ophthalmology', 'Ophtalmologie'), ('psychiatry', 'Psychiatrie'), ('orthopedics', 'Orthopédie'), ('neurology', 'Neurologie'), ('oncology', 'Oncologie'), ('endocrinology', 'Endocrinologie'), ('gastroenterology', 'Gastro-entérologie'), ('pulmonology', 'Pneumologie'), ('nephrology', 'Néphrologie'), ('rheumatology', 'Rhumatologie'), ('urology', 'Urologie'), ('radiology', 'Radiologie'), ('anesthesiology', 'Anesthésie'), ('emergency', "Médecine d'urgence"), ('other', 'Autre')], max_length=100, null=True),
        ),
    ]
