# Generated by Django 4.2.7 on 2025-10-20 14:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorWeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], max_length=10, verbose_name='Jour de la semaine')),
                ('is_available', models.BooleanField(default=True, help_text='Le médecin travaille-t-il ce jour?', verbose_name='Disponible')),
                ('morning_start', models.TimeField(blank=True, help_text='Heure de début de la session du matin', null=True, verbose_name='Début matin')),
                ('morning_end', models.TimeField(blank=True, help_text='Heure de fin de la session du matin', null=True, verbose_name='Fin matin')),
                ('afternoon_start', models.TimeField(blank=True, help_text="Heure de début de la session de l'après-midi", null=True, verbose_name='Début après-midi')),
                ('afternoon_end', models.TimeField(blank=True, help_text="Heure de fin de la session de l'après-midi", null=True, verbose_name='Fin après-midi')),
                ('appointment_duration', models.PositiveIntegerField(default=30, help_text='Durée en minutes de chaque rendez-vous', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)], verbose_name='Durée rendez-vous (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horaire hebdomadaire',
                'verbose_name_plural': 'Horaires hebdomadaires',
                'ordering': ['doctor', 'day_of_week'],
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='DoctorExceptionalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text="Date de l'horaire exceptionnel", verbose_name='Date')),
                ('morning_start', models.TimeField(blank=True, null=True, verbose_name='Début matin')),
                ('morning_end', models.TimeField(blank=True, null=True, verbose_name='Fin matin')),
                ('afternoon_start', models.TimeField(blank=True, null=True, verbose_name='Début après-midi')),
                ('afternoon_end', models.TimeField(blank=True, null=True, verbose_name='Fin après-midi')),
                ('appointment_duration', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)], verbose_name='Durée rendez-vous (min)')),
                ('reason', models.CharField(blank=True, help_text="Raison de l'horaire exceptionnel (optionnel)", max_length=100, verbose_name='Raison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='exceptional_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horaire exceptionnel',
                'verbose_name_plural': 'Horaires exceptionnels',
                'ordering': ['date'],
                'unique_together': {('doctor', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DoctorDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date du congé', verbose_name='Date')),
                ('reason', models.CharField(blank=True, help_text='Raison du congé (optionnel)', max_length=100, verbose_name='Raison')),
                ('is_full_day', models.BooleanField(default=True, help_text='Cochez si absent toute la journée', verbose_name='Journée complète')),
                ('unavailable_start', models.TimeField(blank=True, help_text='Heure de début (si absence partielle)', null=True, verbose_name='Début indisponibilité')),
                ('unavailable_end', models.TimeField(blank=True, help_text='Heure de fin (si absence partielle)', null=True, verbose_name='Fin indisponibilité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Congé médecin',
                'verbose_name_plural': 'Congés médecins',
                'ordering': ['date'],
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
