# Generated by Django 4.2.7 on 2025-10-22 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0002_doctorweeklyschedule_doctorexceptionalschedule_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorweeklyschedule",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (0, "Lundi"),
                    (1, "Mardi"),
                    (2, "Mercredi"),
                    (3, "Jeudi"),
                    (4, "Vendredi"),
                    (5, "Samedi"),
                    (6, "Dimanche"),
                ],
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="Jour de la semaine",
            ),
        ),
    ]
