# Generated by Django 5.0 on 2025-11-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_convert_day_of_week_to_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('online', 'En ligne'), ('presentiel', 'Présentiel')], default='presentiel', help_text='Type of appointment: online or in-person', max_length=20),
        ),
    ]
