# Generated by Django 4.2.7 on 2025-10-08 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medical_documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_primary_doctor_alter_patient_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistReferralPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to=medical_documents.models.referral_pdf_path, verbose_name='Fichier PDF')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('patient_summary', models.TextField(help_text='Informations du patient incluses dans le PDF', verbose_name='Résumé patient')),
                ('referral_reason', models.TextField(help_text='Raison de la référence au spécialiste', verbose_name='Motif de référence')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='Notes additionnelles')),
                ('patient_specialist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_pdf', to='patients.patientspecialist', verbose_name='Assignation spécialiste')),
            ],
            options={
                'verbose_name': 'PDF de Référence Spécialiste',
                'verbose_name_plural': 'PDFs de Référence Spécialiste',
                'db_table': 'specialist_referral_pdfs',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('medical_test', 'Résultat de test médical'), ('prescription', 'Ordonnance'), ('medical_image', 'Image médicale (radiographie, scanner, etc.)'), ('report', 'Rapport médical'), ('insurance', "Document d'assurance"), ('other', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('file', models.FileField(upload_to=medical_documents.models.patient_document_path, verbose_name='Fichier')),
                ('is_visible_to_all_doctors', models.BooleanField(default=True, help_text='Si coché, tous les médecins du patient peuvent voir ce document', verbose_name='Visible à tous les médecins')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléchargement')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient', verbose_name='Patient')),
                ('related_specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_documents', to='patients.patientspecialist', verbose_name='Spécialiste associé')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Téléchargé par')),
            ],
            options={
                'verbose_name': 'Document Patient',
                'verbose_name_plural': 'Documents Patients',
                'db_table': 'patient_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
